name: Build and deploy Node.js app to Azure Web App - ois-portalAdmin

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install backend dependencies
        run: npm install

      - name: Build frontend
        run: |
          cd webapp
          npm install
          CI=false npm run build

      - name: Create startup.txt
        run: echo "cd site/wwwroot/server && pm2 start server.js" > startup.txt

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FB1D9E01929143139634A11954E759B5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0364CEADF4AA497F9D304F65B0E018EC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C83E7B1C437945EF961A6D9674FA1045 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ois-portalAdmin'
          slot-name: 'Production'
          package: .

      - name: Set startup command
        run: |
          az webapp config set --name ois-portalAdmin --resource-group Testes-Luiz --startup-file "cd site/wwwroot/server && pm2 start server.js"
